# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MappingEcosystemServices
                                 A QGIS plugin
 This plugin maps ecosystems
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-10-08
        copyright            : (C) 2019 by NaturalGIS
        email                : luis.calisto@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MappingEcosystemServices class from file MappingEcosystemServices.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mapping_ecosystem_services import MappingEcosystemServices
    return MappingEcosystemServices(iface)
